version: 1.0.{build}

cache:
  - C:\ProgramData\chocolatey\cache

environment:
  matrix:
    - perl: "5.14.4.1"
    - perl: "5.16.3.20170202"
    - perl: "5.18.4.1"
    - perl: "5.20.3.3"
    - perl: "5.22.3.1"
    - perl: "5.24.3.1"
    - perl: "5.26.1.1"
    - perl: system

platform:
  - x86
  - x64

matrix:
  exclude:
    - platform: x64
      perl: system

install:
  - if /I not %perl% == system if /I %PLATFORM% == x86 (set x86=--forcex86) else (set "x86= ")
  - if /I not %perl% == system choco config set cacheLocation C:\ProgramData\chocolatey\cache
  - if /I not %perl% == system cinst StrawberryPerl --version %perl% %x86% --allow-empty-checksums
  - if /I not %perl% == system path C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\strawberry\c\bin;%PATH%
  - if /I %perl% == system curl -fsS -o C:\dmake.zip http://www.cpan.org/authors/id/S/SH/SHAY/dmake-4.12.2.2.zip
  - if /I %perl% == system 7z x -oC:\ C:\dmake.zip
  - if /I %perl% == system path C:\MinGW\bin;C:\dmake;%PATH%
  - perl -V
  - perl Makefile.PL
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)" regen

build_script:
  - perl Makefile.PL
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)"

test_script:
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)" test
